greenbone/pheme

.gitignore
pheme/settings.py
pheme/transformation/scanreport/gvmd.py
pheme/transformation/scanreport/renderer.py
template/host_detailed_report.html
tests/test_gvmd_scanreport_datatransformation.py

the logo in host_detailed_report.html is configurable via settings.py
the allowed hosts in settings.py can be overriden via env parameter
gvmd sometimes sends report[report[data]] and sometimes report[data] to
reflect that gvmd does check if report[report is there if so use
report[report else report
**Checklist**:

make template logo configurable, add allow hosts, fix report resolving

---

CHANGELOG.md
pheme/renderer.py
pheme/transformation/scanreport/model.py
pheme/urls.py
pheme/views.py
poetry.lock
pyproject.toml
tests/test_report_data_description.py

**What**:
Creates a new endpoints to get a markdown table of scanreport model description.
**Why**:
To have an easy way to include the data description within a confluence page.
**How**:
```
curl -H 'accept: text/markdown+table' localhost:8000/scanreport/data/description
```
**Checklist**:

Add endpoint for scanreport model description

---

pheme/settings.py

**What**:
Make basepath configurable
**Why**:
So the defaults can be used even though pheme got installed and started via pip
**How**:
start pheme with a different BASE_PATH and see if the contents are reachable via localhost:8000/static/a_name
**Checklist**:

make basepath configureable

---

pheme/parameter.py

**What**:
While rendering pheme was unable to load the parameter due to missing from_path
**Why**:
**How**:
**Checklist**:

fix bug of missing path while load_params when rendering

---

CHANGELOG.md
pheme/renderer.py
pheme/views.py
tests/test_report_generation.py

**What**:
Add xml as well as csv report response. Add possibility to not include overview information.
**Why**:
**How**:
- upload a scanreport
- call:
curl -H "accept: application/xml" -o /tmp/test.xml http://localhost:8000/report/$ID?without_overview=true
curl -H "accept: text/csv" -o /tmp/test.csv http://localhost:8000/report/$ID?without_overview=true
**Checklist**:

add xml render possibility to ignore overview

---

pheme/parameter.py
pheme/urls.py
tests/test_parameter.py
tests/test_report_generation.py

**What**:
Add a possibility to merge a json object into the global parameter.
**Why**:
To make the transfer from developer parameter.json into report-formats easier.
**How**:
```
curl -X PUT -H "content-type: application/json" localhost:8000/parameter\
-d @path_to_json.json\
-H 'x-api-key: SECRET_KEY_missing_using_default_not_suitable_in_production'
```
verify parameter json of your running pheme.
**Checklist**:

add possibility to merge json dict into global parameter

---

pheme/parameter.py
pheme/transformation/scanreport/renderer.py
tests/test_report_generation.py

**What**:
Due to different requirements for html structure for pdf and html reports this commit separated those two templates to prevent too many if HTML, if PDF ...
Add `text/scss`as mimetype in parameter to allow form upload of sass.
**Why**:
**How**:
**Checklist**:

Separate html and pdf template

---

CHANGELOG.md
pheme/parameter.py
pheme/scripts/parameter.py
pheme/transformation/scanreport/renderer.py
poetry.lock
pyproject.toml

**What**:
remove libsass support because it is deprecated and it is easier to use dart when creating report-format than it is within pheme.
https://sass-lang.com/blog/libsass-is-deprecated
**Why**:
**How**:
**Checklist**:

remove libsass

---

CHANGELOG.md
pheme/settings.py
pheme/transformation/scanreport/gvmd.py
pheme/transformation/scanreport/model.py
tests/generate_test_data.py
tests/test_report_generation.py

**What**:
To make it easier to display nvt information on the host detail page this pr adds the information:
```
...
"host": "hostname",
"threats": {
"high": 3,
"medium": 3,
"low": 1,
"total": 7,
"highest": "High"
},
...
```
**Why**:
**How**:
**Checklist**:

add nvt statistics per host result

---

CHANGELOG.md
pheme/transformation/scanreport/renderer.py
tests/test_report_generation.py

**What**:
Unfortunately WeasyPrint does not support inline svg at all, since we
need that functionality to create pictures dynamically based on
report-formats.
This workaround does look for tags with svg and then creates an img
element with base64 image content of that.
We are painfully aware that we lose css information with that method,
but the conclusion is that it is better to may define design element twice
(in the svg and in css) than to not have this possibility at all.
**Why**:
**How**:
Create an pdf-report template with svg content in it. Create a pdf and verify that the svg is displayed.
**Checklist**:

adds a workaround for inline svg and WeasyPrint

---

CHANGELOG.md
pheme/transformation/scanreport/gvmd.py
pheme/transformation/scanreport/model.py

In the vulnerabilty report there is the need to have severity
information easily accessable per host.
You can verify the severity information with a host result by uploading
an report and create a json representation of a report and then e.g.
with `jq '.results[0].severities' `.
**What**:
**Why**:
**How**:
**Checklist**:

add severity information into host overview

---

CHANGELOG.md
pheme/settings.py
pheme/templatetags/__init__.py
pheme/templatetags/charts.py
pheme/transformation/scanreport/gvmd.py

To be capable of change the charts more transparently for templates the
chart creation moved from within the datastructure as data links to
within the template as svg via custom tags.
The data changes therefore as well: from containing the actual charts to
just providing the data in a more or less standardized fashion.
This commit contains the custom_tags:
- pie_chart
- h_bar_chart
those can be used within a template by
{{ overview.nvts | pie_chart }}
{{ overview.hosts | h_bar_chart }}
**What**:
**Why**:
**How**:
**Checklist**:

create templatetags for charts instead of creating it in gvmd

---

pheme/parameter.py
pheme/settings.py

Due to the delivery method of data-objects it can happen that the
parameter.json will be overridden when the feed version has a newer date
than the system parameter.
For this case it is necessary to have two separated files, one for
system specific adaptations and one delivered via data-objects.
Therefor a new path variable DEFAULT_PARAMETER_ADDRESS is introduced.
When loading parameter the two parameter will be combined in a way that
the system parameter json may override the default parameter.
**What**:
**Why**:
**How**:
**Checklist**:

add second path for default parameter

---

pheme/settings.py
poetry.lock
pyproject.toml

instead of using a default value when PHEME_API_KEY is not set pheme is
now trying to load or create a new api_key within either:
- PHEME_CONFIGURATION_PATH (env variable)
- /var/lib/pheme
- /tmp/
folder.
Setting the version of django and rest-framework to the one within
debian buster (backports)
**What**:
**Why**:
**How**:
**Checklist**:

change API_KEY handling from using default value to creating new

---

CHANGELOG.md
pheme/settings.py
pheme/templatetags/dynamic_template.py
tests/test_report_generation.py

With `dynamic_template` it is possible to upload a template as parameter
and use it within an different template.
As an example when you upload a template with:
```
<h1>{{ High }}</h1>
```
and key `nvts_template`
When you then upload another template and want to use the previous
template within that you can load `dynamic_template` and use it like:
```
{% load dynamic_template %}
<html>
{{ overview.nvts | dynamic_template:"nvts_template" }}
</html>
```
**What**:
**Why**:
**How**:
**Checklist**:

add possibility to use dynamic_template within parameter

---

CHANGELOG.md
pheme/settings.py
pheme/templatetags/charts/h_bar.py
pheme/templatetags/charts/pie.py
tests/test_report_generation.py

When a report does not contain a result than total was zero on a pie
chart which lead to division by zero. Fix is to return no diagram when
there are no results.
Also adds a changelog entry and fix for logs when there is no /dev/log mainly for docker.
**What**:
**Why**:
**How**:
**Checklist**:

fix bug when report does not contain result

---

CHANGELOG.md
pheme/templatetags/charts/__init__.py
pheme/templatetags/charts/h_bar.py
pheme/templatetags/charts/pie.py
pheme/templatetags/charts/treemap.py
poetry.lock

**What**:
Add font-family and size to text elements of charts and set the default values of those to 'Droid Sans' and 10.
**Why**:
To reflect the charts within the mockup vision as good as possible.
Although there is CHANGELOG entry there are no unit tests for it, mainly because font changes are purely visual without a technical impact.
**How**:
Create a PDF and verify that the font is smaller than on a previous version within the charts.
**Checklist**:

Add font-family and size to text elements within charts

---

pheme/authentication.py

From codespell:
```
./pheme/authentication.py:34: falsly ==> falsely
```

Fix a typo.

---

CHANGELOG.md
pheme/templatetags/readable_timeformat.py
tests/generate_test_data.py
tests/test_format_time.py

To standardize the presentation of date time within gsa and the report
format a template function 'format_time' is introduced.
**What**:
**Why**:
**How**:
**Checklist**:

Add functionality to transform iso datetime to human readable

---

CHANGELOG.md
pheme/transformation/scanreport/gvmd.py

The actual severity of a host should be a float not an int, every
processed value based of severity should be an int for easier handling
within the templates.
**What**:
**Why**:
**How**:
**Checklist**:

Change host.severity from int to float

---

CHANGELOG.md
pheme/transformation/scanreport/renderer.py

On some machines the RAM is not sufficient for larger reports therefore
a limitation got introduced.
It will be configured via data-objects parameter.json.
**What**:
**Why**:
**How**:
**Checklist**:

Add artificial limit for PDF renderer

---

README.md

swagger got removed a while ago while packging it for debian:stable due
to older django version. Unfortunately removing the swagger API in the
doc got not removed.
**What**:
**Why**:
**How**:
**Checklist**:

Remove API doc entry

---

CHANGELOG.md
pheme/templatetags/charts/h_bar.py
pheme/views.py
tests/test_report_generation.py

Add possibility to add a title to the count numbers on the x-axis
To use the whole functionality of bar_h without having to specify every
parameter in order it is also registered as a simpletag instead of just
a filter.
This allows templates to use the chart by calling it:
```
{%  h_bar_chart overview.hosts x_title="Vulnerabilitites" %}
```
In addition to that there is also a new field called pheme_version with
just the numbers of set version.
This allows feature_toggles within the templates e.g.:
```
{% if pheme_version and pheme_version > 2144 %}
{%  h_bar_chart overview.hosts x_title="Vulnerabilitites" %}
{% else %}
{{ overview.hosts |  h_bar_chart }}
{% end %}
```
**What**:
**Why**:
**How**:
**Checklist**:

Extend bar chart with x titles, add bar chart as tag

---

pheme/settings.py

**What**:
In GOS 21.10.0 the vulnerability reports where empty because the
path to the file "default-parameter.json" was wrong because of the
wrong value of the parameter GOS_VERSION. So it had to be changed.
**Why**:
This is a small bug-fix.
Addresses AP-1874
**How**:
Regrettably I can not test, if it works on a GOS 21.10 system. The way I can
run the generation of vulnerability reports on my system is presumably different.
**Checklist**:

Changed the parameter GOS_VERSION from "21.04" to "21.10".

---

.docker/pheme.Dockerfile
.github/workflows/container.yml

Container image builds by using bullseye as base
Using bullseye seems to be the better solution then to upgrade to bookworm and have to fiddle with the pip installations. Just keep the thing stable.

Fix: Container image builds by using bullseye as base

---

.github/dependabot.yml

Set Dependabot target branch and commit message prefix
From now on, only the main branch will be used for development and the prefix is used for generating the conventional commit release notes.

Change: Set Dependabot target branch and commit message prefix

---

pheme/transformation/scanreport/gvmd.py
pheme/transformation/scanreport/model.py

The main hostnames and a list of all hostnames are added to each host
and scan results now also have their associated hostname added.
This allows adding the hostname info to generated reports.
GEA-378

Add hostnames to report data for templates 

---

pheme/transformation/scanreport/gvmd.py

The Vulnerability Report PDF had in special cases only a length of zero bytes (it was empty) when sent by an alert. This is no longer the case.
This is a bug-fix.
GEA-408
Tested manually on my development system.

Fix: Handle missing excerpt in notes / overrides.

---

.github/workflows/ci-python.yml

Add Codecov token to CI workflow
GEA-604

Add Codecov token to CI workflow

---

tests/test_format_time.py
tests/test_report_generation.py

Use a helper to avoid test functions returning non-None.
This is needed for pytest 8.4.0 compatibility. Tests returning non-None are failing in https://github.com/greenbone/pheme/pull/978.
See pytest [changelog](https://github.com/pytest-dev/pytest/releases)
GEA-1110

Test: Ensure test functions return None for pytest 8.4.0 compatibility
