greenbone/pheme

pheme/parser/xml.py, tests/test_xmlparser.py
=> override cdata from #text to text

pheme/transformation/scanreport/renderer.py
=> workaround https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4460

CHANGELOG.md, pheme/renderer.py, pheme/settings.py, pheme/transformation/scanreport/gvmd.py, pheme/transformation/scanreport/model.py, pheme/urls.py, pheme/views.py, poetry.lock, template/pdf_report.css, template/scan_report.html, tests/generate_test_data.py, tests/test_report_generation.py
**What**:
Add chart support for pie and barh charts within reports.
**Why**:
The mockup report contains charts.
**How**:
Create a pdf and verify the charts.
**Checklist**:
=> Add chart support

CHANGELOG.md, pheme/transformation/scanreport/gvmd.py, pheme/transformation/scanreport/model.py, pheme/transformation/scanreport/renderer.py, tests/generate_test_data.py
**What**:
- add host overview to json
- fix error handling
- add stacked bar chart
**Why**:
- to get an easier overview over multiple hosts
- on an unknown id there was a 500 instead of 404 and a proper hint
- for ports top ten we want to have the low, medium, high stacked
**How**:
**Checklist**:
=> host overview, stacked threats for ports chart

pheme/transformation/scanreport/gvmd.py, template/scan_report.html, tests/generate_test_data.py, tests/test_gvmd_scanreport_datatransformation.py, tests/test_report_generation.py
**What**:
Switch from svg to png due to depndency on GDK-Pixbuf.
**Why**:
**How**:
**Checklist**:
=> switch back to png since svg has a dependency to GDK-Pixbuf.

pheme/transformation/scanreport/gvmd.py
**What**:
- shortening label based on percentage of highest amount of nvts
- enhancing size of vulnerability equipment
**Why**:
**How**:
**Checklist**:
=> change count and size for vulnerability_equipment

CHANGELOG.md, pheme/parser/xml.py, pheme/settings.py, pheme/storage.py, pheme/transformation/scanreport/gvmd.py, pheme/transformation/scanreport/renderer.py, pheme/urls.py, pheme/views.py, static/report_format_editor.html, tests/generate_test_data.py, tests/test_gvmd_scanreport_datatransformation.py, tests/test_report_generation.py
**What**:
Add initial Report-Foramt-Editor
**Why**:
So that it is possible to play around with the css and template for pdfs without the need to use the API directly.
**How**:
Start pheme, go to:
```
http://localhost:8000/static/report_format_editor.html
```
1. upload xml report
1. upload html template
1. upload css template
1. upload images
1. create pdf
1. download all
**Checklist**:
=> Report format editor

template/scan_report.html
**What**:
Just a minor typo ... but in the ID of a HTML Tag ....
**Why**:
**How**:
**Checklist**:
=> Typo in html template

pheme/transformation/scanreport/renderer.py, static/report_format_editor.html, template/scan_report.html
**What**:
Add possibility to render a html report not just a pdf report.
**Why**:
**How**:
* upload xml report
* select html via radio button
* upload html template
* upload css template
* upload images
* create html
**Checklist**:
=> add html rendering in report_format_editor

pheme/transformation/scanreport/renderer.py
**What**:
Disable report cache when DEBUG is TRUE
**Why**:
To test css changes without having to upload a report every time.
**How**:
**Checklist**:
=> don't use report cache when on DEBUG

README.md, pheme/transformation/scanreport/gvmd.py
**What**:
Add nvt.solution fields to gvmd and enhanced README.md with additional dependencies.
**Why**: 
**How**:
**Checklist**:
=> Add nvt solution and depndencies to README

pheme/transformation/scanreport/renderer.py, tests/test_report_generation.py
**What**:
To make it easier to distinguish in the json as well when uploading template the template keyword got added to the html template keyword in renderer.
**Why**:
**How**:
**Checklist**:
=> Rename html to template keyword

pheme/transformation/scanreport/renderer.py, poetry.lock, pyproject.toml, tests/test_report_generation.py
**What**:
Add sass compiler as pre renderering step for html and pdf.
**Why**:
scss seems to be favoured by some designer.
**How**:
upload a scss instead of css as `vulnerability_report_pdf_css` and verify that pdf outcome is respecting it.
**Checklist**:
=> Add sass handling

CHANGELOG.md, pheme/datalink.py, pheme/parameter.py, pheme/scripts/parameter.py, pheme/transformation/scanreport/renderer.py, pyproject.toml
**What**:
**Why**:
To be capable of creating a parameter.json for global parameter based on a directory `pheme-create-parameter-json` will be introduced here.
**How**:
Install pheme either via pip or other means:
```
poetry build
pip3 install --user --force dist/pheme-0.0.1.dev2-py3-none-any.whl
```
afterwards run `pheme-create-parameter-json` for global parameter:
```
pheme-create-parameter-json ~/src/peder/pheme-report-formats/global > ~/src/nichtsfrei/pheme/static/parameter.json
```
**Checklist**:
=> Script to create parameter json

CHANGELOG.md, pheme/authentication.py, pheme/get_user_information.py, pheme/parameter.py, pheme/settings.py, pheme/transformation/scanreport/renderer.py, tests/test_get_username_and_role.py, tests/test_parameter.py, tests/test_report_generation.py
**What**:
Add possibility to add gsad user specific parameter to pheme.
**Why**:
To allow department specific changes which are not meant to be in the global parameter it is necessary to have the possibility to add specific elements.
**How**:
- login into gsad, copy the token as well as GSAD_ID from a gmp call and use them with pheme:
``` 
curl 'http://localhost:8000/parameter?token=TOKEN'  -H 'Cookie: GSAD_SID=GSAD_SID' -X PUT --form main_color=#ccc
```
- upload a report
- generate report via the same token and GSAD_SID parameter:
```
curl 'http://localhost:8000/report/ID?token=TOKEN' -H "accept: text/html"  -H 'Cookie: GSAD_SID=GSAD_SID'
```
**Checklist**:
=> Allow user specific changes

pheme/transformation/scanreport/gvmd.py
**What**:
remove complex distribution in favor of a easy bar chart and sort values of host top then by [[ 'High', "Medium", "Low" ]]
**Why**:
**How**:
**Checklist**:
=> remove distribution chart in favor of easier bar chart

.circleci/config.yml, pheme/__init__.py, setup.py
**What**:
add setup.py to enable deb packaging.
**Why**:
**How**:
**Checklist**:
=> add setup.py for packaging

setup.py
**What**:
remove exclude test from setup.py
**Why**:
So that the setup.py can be used within the GOS ci.
**How**:
**Checklist**:
=> applied patch to use setup.py in gos ci

pheme/templatetags/charts/__init__.py, pheme/templatetags/charts/h_bar.py, pheme/templatetags/charts/treemap.py
**What**:
Add legend to bar_chart and treemap, so far barchart and the treemap don't have a legend to describe the colors.
**Why**:
**How**:
**Checklist**:
=> Add chart legend

pheme/settings.py
The target environment GOS is using:
- syslog
- DEBUG should be false
- ALLOWED_HOST should be * (actual control is done via nginx)
**What**:
**Why**:
**How**:
**Checklist**:
=> set defaults to be useable for GOS

CHANGELOG.md, pheme/transformation/scanreport/gvmd.py, tests/generate_test_data.py, tests/test_gvmd_scanreport_datatransformation.py
Before only the latest references was added to the list, fix that by
loading the previous found refs before adding the new one into the list.
**What**:
**Why**:
**How**:
**Checklist**:
=> add all references of a nvt into references

pheme/templatetags/charts/h_bar.py, tests/test_report_generation.py
**What**:
When trying to create a report based on only log events than creating a bar chart was failing with an error because the max severity was 0.
Please merge after 180.
**Why**:
**How**:
**Checklist**:
=> Error when log only

CHANGELOG.md, pheme/transformation/scanreport/gvmd.py, pheme/transformation/scanreport/model.py, pheme/transformation/scanreport/renderer.py
**What**:
Removes the protocol version within report data and resets version to parameter.json version
**Why**:
**How**:
**Checklist**:
=> Remove protocol version in favor of parameter version

pheme/templatetags/charts/__init__.py, pheme/templatetags/charts/h_bar.py, pheme/templatetags/charts/pie.py, pheme/templatetags/charts/treemap.py
**What**:
Change default font from Droid Sans to Dejavu Sans within graphs.
**Why**:
Most systems don't have Droid Sans installed but have Dejavu Sans
**How**:
**Checklist**:
=> Default font

CHANGELOG.md, pheme/templatetags/charts/__init__.py, pheme/templatetags/charts/h_bar.py, pheme/templatetags/charts/pie.py, pheme/templatetags/charts/treemap.py
Due to unspecificied units firefox didn't not set the correct font size.
**What**:
**Why**:
**How**:
**Checklist**:
=> Set px to font-size because

CHANGELOG.md, pheme/transformation/scanreport/gvmd.py
It will fix the count of Low if a entry is e.g. a Log entry or something
similar.
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: Counts threat as Low when actually unknown

CHANGELOG.md, pheme/settings.py, poetry.lock, pyproject.toml
sentry will only be loaded when SENTRY_DNS_PHEME is set as an
environment variable otherwise it will be ignored.
**What**:
**Why**:
**How**:
**Checklist**:
=> Integrate sentry

.github/workflows/deploy-pypi.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add deploy workflow for GitHub Actions

.github/workflows/codeql-analysis-python.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add CodeQL Workflow to scan code with GitHub Actions

.github/workflows/release-pontos.yml, poetry.lock, pyproject.toml
**What**:
**Why**:
**How**:
**Checklist**:
=> Workflow to release with pontos-release

.docker/pheme.Dockerfile, .github/workflows/container.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Init pheme container

pheme/transformation/scanreport/gvmd.py
**What**:
If the maximum severity for a host is 0, now no severity is marked
in the host overview (before the 10 was marked).
**Why**:
This is a small bug-fix.
**How**:
Tested some reports with different severities.
**Checklist**:
=> Small amendment of the host overview.

.mergify.yml
**What**:
Add settings for mergify
**Why**:
Use mergify to backport PRs
**How**:
**Checklist**:
=> Add settings for mergify

.docker/pheme.Dockerfile, .dockerignore, .github/workflows/container.yml
**What**:
Improve building pheme container
DEVOPS-353
**Why**:
Allow building the container using the dockerfile without having to know about the wheel distributable. Use more flexible action for container labels and tags.
**How**:
**Checklist**:
=> Use docker meta action

.docker/pheme.Dockerfile
**What**:
Fix missing `-` in `--from:`
**Why**:
**How**:
**Checklist**:
=> Fix pheme.Dockerfile

pheme/transformation/scanreport/gvmd.py
For hosts with only a single detail the report did not work. So a distinction was added between a single detail and a list of details to make it work in both cases.
This is a bug-fix.
GEA-209
Tested manually on my local development environment.
=> Added a differentiation between a single detail and a list of details.

pheme/transformation/scanreport/gvmd.py
The results in the report data available to the template now include overrides and notes if available.
This allows including them in the reports.
GEA-85
=> Add: Add overrides and notes for results

pheme/settings.py, poetry.lock
Update dependencies and fix formatting
Failing tests after dependabot version updates
GEA-478
=> Update dependencies fix formatting

README.md
nb: No PR template on purpose for such a minor and obvious change.
=> Doc: Update company name in README.md
